from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

PROCESSED_METRICS_PATH = Path("data/processed/weekly_metrics.json")
REPORTS_DIR = Path("reports")


def load_metrics(path: Path = PROCESSED_METRICS_PATH) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt_dt(s: str | None) -> str:
    if not s:
        return "Unknown"
    # created_date looks like: 2025-12-22T02:20:56.000
    # Keep it readable:
    return s.replace("T", " ").replace(".000", "")


def build_markdown(metrics: dict[str, Any]) -> str:
    total = metrics.get("total_rows", 0)
    dt_min = _fmt_dt(metrics.get("window_start") or metrics.get("created_date_min"))
    dt_max = _fmt_dt(metrics.get("window_end") or metrics.get("created_date_max"))

    top_complaints = metrics.get("top_complaints", [])[:15]
    top_boroughs = metrics.get("top_boroughs", [])
    status_counts = metrics.get("status_counts", [])

    lines: list[str] = []
    lines.append("# NYC 311 Weekly Report")
    lines.append("")
    lines.append(f"**Window:** {dt_min} → {dt_max}")
    lines.append(f"**Total requests:** {total:,}")
    lines.append("")

    # A tiny “executive summary” (deterministic, no LLM yet)
    if top_complaints:
        top1, top1_count = top_complaints[0]
        lines.append(f"## Summary")
        lines.append(f"- Most common issue: **{top1}** ({top1_count:,} requests)")
        if len(top_complaints) >= 2:
            top2, top2_count = top_complaints[1]
            lines.append(f"- Second: **{top2}** ({top2_count:,} requests)")
        lines.append("")

    lines.append("## Top complaint types (top 15)")
    lines.append("")
    lines.append("| Rank | Complaint type | Count |")
    lines.append("|---:|---|---:|")
    for i, (name, count) in enumerate(top_complaints, start=1):
        lines.append(f"| {i} | {name} | {count:,} |")
    lines.append("")

    lines.append("## Requests by borough")
    lines.append("")
    lines.append("| Borough | Count |")
    lines.append("|---|---:|")
    for b, c in top_boroughs:
        lines.append(f"| {b} | {c:,} |")
    lines.append("")

    lines.append("## Status breakdown")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|---|---:|")
    for s, c in status_counts:
        lines.append(f"| {s} | {c:,} |")
    lines.append("")

    lines.append("---")
    lines.append("Generated by `nyc311-weekly-report`.")
    lines.append("")
    return "\n".join(lines)


def save_report(markdown: str, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown, encoding="utf-8")


def generate_report() -> Path:
    metrics = load_metrics()
    # Use today's date for the filename; later we can use week-start
    today = datetime.now().strftime("%Y-%m-%d")
    out = REPORTS_DIR / f"weekly_report_{today}.md"
    save_report(build_markdown(metrics), out)
    return out
